import type { ClientDocsInput } from '../generators/types'

// Plain-language copy for people with little tech experience (Cuban Spanish, «tú»).
export const clientDocsInput = {
  appName: 'LensSpace',
  clientName: 'la óptica',
  appUrl: 'https://lensspace.vercel.app',
  modules: [
    {
      name: 'Panel principal',
      description: 'Es la primera pantalla que ves al entrar. De un vistazo te dice cuántos pedidos hay en curso, cuánto se cobró hoy, qué está listo para entregar y cuánto dinero falta por cobrar. A la izquierda está el menú con todas las secciones.',
      image: { src: '/manual/panel.jpg', alt: 'Panel principal: arriba los números del día y a la izquierda el menú' },
      endUserActions: ['Para ir a otra parte del sistema, toca su nombre en el menú de la izquierda.', 'En el teléfono el menú está escondido: toca el botón de las tres rayitas para abrirlo.', 'Para venderle a un cliente, toca el botón verde «Nueva venta».', 'Cuando termines, toca el botón de salir que está al lado de tu nombre, abajo del menú.'],
      adminActions: ['En «Pulso del negocio» puedes ver las ventas por sucursal, por vendedor y por fechas.', 'Escoge lo que quieres ver y toca «Actualizar métricas».', 'Ahí ves cuánto se vendió, cuánto se cobró, cuánto falta por cobrar, qué pedidos tuvieron problemas y qué productos se venden más.'],
    },
    {
      name: 'Clientes',
      description: 'Aquí guardas los datos de cada persona que viene a la óptica: nombre, teléfonos y dirección. Así no tienes que preguntarle lo mismo cada vez que vuelva.',
      image: { src: '/manual/clientes.jpg', alt: 'Ficha de cliente nuevo: el sistema avisa si ya existe alguien parecido' },
      endUserActions: ['Antes de crear un cliente, búscalo por su nombre o por su teléfono. Puede que ya esté guardado.', 'Si no aparece, toca «Nuevo cliente» y escribe su nombre completo y su teléfono.', 'Puedes poner hasta cinco teléfonos (por ejemplo, el de la casa y el móvil).', 'Si el cliente quiere que le avisen por WhatsApp, marca la casilla de WhatsApp.', 'Si el sistema te dice que ya hay clientes parecidos, revisa que no sea la misma persona antes de crear otra ficha.', 'Para cambiar un dato, abre la ficha del cliente y toca editar.', 'Desde la ficha también puedes ver todos los pedidos de ese cliente.'],
      adminActions: ['Ves los clientes de todas tus sucursales.', 'En cada cliente ves cuántos trabajos tiene en curso y cuántos ya terminó.'],
    },
    {
      name: 'Recetas',
      description: 'La receta es la graduación que mandó el médico u optometrista. Aquí se copia para que el laboratorio haga los cristales bien. Nada se borra: si te equivocas, se corrige y el sistema guarda las dos versiones.',
      image: { src: '/manual/recetas.jpg', alt: 'Pantalla de recetas: un cuadro para el ojo derecho (OD) y otro para el izquierdo (OI)' },
      endUserActions: ['Escoge primero al cliente.', 'Copia los números de la receta en los cuadros: OD es el ojo derecho y OI es el ojo izquierdo.', 'Si la receta trae más datos (fecha, nombre del médico, observaciones), anótalos también.', 'Puedes tomarle una foto al papel de la receta y subirla, o subir un PDF (que no pese más de 10 MB).', 'Toca «Guardar receta».', 'Si te equivocaste en un número, toca «Corregir». La receta vieja no se pierde: queda guardada en el historial.'],
      adminActions: ['En el historial ves todas las correcciones de cada receta y quién las hizo.'],
    },
    {
      name: 'Catálogo y precios',
      description: 'Es la lista de todo lo que vendes: armaduras, tipos de cristal y sus precios. Cada producto puede tener su precio en CUP o en USD.',
      image: { src: '/manual/catalogo.jpg', alt: 'Catálogo: cada producto con su precio y, a la derecha, la suma de lo escogido' },
      endUserActions: ['Puedes marcar varios productos para ver cuánto costaría todo junto.', 'Escribe la tasa del día (cuántos CUP vale 1 USD) para ver el total en CUP.', 'Si escoges la receta del cliente, el sistema te avisa si hace falta algún recargo por la graduación.', 'Toca «Calcular precio» para ver el total antes de venderle al cliente.'],
      adminActions: ['Toca «Nuevo artículo propio» para agregar un producto que solo vende tu óptica.', 'Toca el lápiz de un producto para cambiarle el precio, la moneda, lo que te cuesta a ti o para ponerlo como no disponible.'],
    },
    {
      name: 'Nueva venta',
      description: 'Aquí atiendes al cliente de principio a fin: escoges al cliente, su receta y los espejuelos, le dices el precio y, cuando él dice que sí, se crea el pedido.',
      image: { src: '/manual/venta.jpg', alt: 'Nueva venta: arriba el cliente y la receta, abajo los productos y a la derecha el total' },
      endUserActions: ['Toca «Nueva venta».', 'Busca al cliente. Si es nuevo, toca «Nuevo cliente» ahí mismo, sin salir de la venta.', 'Escoge su receta, o toca «Nueva receta» si trae una nueva.', 'Escribe la tasa del día (cuántos CUP vale 1 USD).', 'Toca la armadura y los cristales que el cliente quiere.', 'Si le haces un precio especial, cámbialo en el producto y explica por qué.', 'Revisa el total con el cliente.', 'Si el cliente lo va a pensar, toca «Guardar cotización».', 'Si el cliente dice que sí, toca «Cliente acepta · crear pedido».', 'Si deja dinero adelantado, anótalo enseguida en «Registrar efectivo».'],
      adminActions: ['En cada venta puedes ver el precio normal, el precio que se cobró y por qué se cambió.', 'Si cambias un precio del catálogo después de cotizar, el vendedor tiene que volver a calcular y confirmar con el cliente.'],
    },
    {
      name: 'Pedidos y cobros',
      description: 'Aquí está cada pedido con lo que cuesta, lo que ya pagó el cliente y lo que le falta por pagar. También ves todo lo que ha pasado con el pedido, paso a paso.',
      image: { src: '/manual/pedidos.jpg', alt: 'Pedidos: a la izquierda la lista y a la derecha el pedido escogido, con lo que falta por pagar' },
      endUserActions: ['Busca el pedido por el nombre del cliente.', 'Usa los botones «Con saldo», «Por entregar» o «Entregados» para ver solo esos pedidos.', 'Toca un pedido para ver cuánto cuesta, cuánto pagó y cuánto le falta.', 'Para cobrar, escribe la cantidad, escoge CUP o USD y toca «Registrar pago».', 'Si paga todo lo que falta, toca «Cobrar saldo completo».', 'Cuando los espejuelos estén listos y revisados, toca «Avisar: listo para recoger» para mandarle un WhatsApp al cliente.', 'Cuando el cliente se lleve sus espejuelos, toca «Marcar como entregado». Solo se puede si ya pagó todo.'],
      adminActions: ['Ves los pedidos de todas tus sucursales.', 'Puedes ver qué cobros se hicieron después de cerrar la caja.'],
    },
    {
      name: 'Producción',
      description: 'Aquí se sigue el trabajo del laboratorio (cristalero) y del montador. Cada uno ve solo los trabajos que le tocan y nunca ve los precios ni los datos del cliente.',
      image: { src: '/manual/produccion.jpg', alt: 'Producción: cada tarjeta es un trabajo, con su estado y el botón del siguiente paso' },
      endUserActions: ['Abre el trabajo que te tocó.', 'Toca «Ver receta de fabricación» para ver la graduación que tienes que hacer.', 'Toca el botón grande para avanzar al siguiente paso (por ejemplo «Iniciar fabricación» y después «Marcar trabajo listo»).', 'Si algo salió mal (un cristal rayado, una medida mala), toca «Incidencia», explica qué pasó y di quién paga el arreglo.'],
      adminActions: ['Toca «Asignar trabajo» para mandarle los cristales al cristalero o el montaje al montador.', 'Cuando el trabajo vuelva, toca «Marcar recibido» y después «Marcar revisado».', 'Si hubo una incidencia, toca «Aceptar repetición» para que se haga el trabajo otra vez. El trabajo malo queda guardado para que se sepa qué pasó.'],
    },
    {
      name: 'Caja y cierres',
      description: 'Aquí cuentas el dinero en efectivo al final del día. Cada vendedor tiene su caja y cada moneda (CUP y USD) se cierra por separado.',
      image: { src: '/manual/caja.jpg', alt: 'Caja: el sistema dice cuánto debería haber y tú escribes cuánto contaste' },
      endUserActions: ['Escoge tu caja del día y la moneda.', 'Mira cuánto dinero dice el sistema que deberías tener.', 'Cuenta los billetes que tienes de verdad.', 'Escribe lo que contaste y toca «Cerrar caja del día».', 'Si después de cerrar alguien te paga, no pasa nada: vuelve a la caja y toca «Generar complementario».'],
      adminActions: ['Puedes ver las cajas por fecha, por sucursal y por vendedor.', 'Si lo contado no coincide con lo que debería haber, verás la diferencia.', 'Los cierres no se pueden cambiar después: quedan guardados tal como se hicieron.'],
    },
    {
      name: 'Equipo',
      description: 'Aquí el dueño invita a los trabajadores (vendedores, cristaleros y montadores) y les quita el acceso cuando ya no trabajan con la óptica.',
      image: { src: '/manual/equipo.jpg', alt: 'Invitar a un trabajador: nombre, correo, qué trabajo hace y en qué sucursal' },
      endUserActions: [],
      adminActions: ['Toca «Invitar miembro».', 'Escribe su nombre y su correo, escoge qué trabajo hace y en qué sucursal.', 'Toca «Enviar invitación». Si no le llega el correo, puedes copiar la invitación y mandársela por WhatsApp.', 'Para cambiar a un vendedor de sucursal, ábrelo y escoge la nueva.', 'Si alguien deja de trabajar contigo, toca «Desactivar acceso». Si vuelve, toca «Reactivar acceso».'],
      audience: 'admin',
    },
    {
      name: 'Organizaciones (solo equipo de LensSpace)',
      description: 'Esta parte la usa únicamente el equipo de LensSpace para dar de alta ópticas nuevas y ayudarlas. Los dueños de óptica no la ven.',
      endUserActions: [],
      adminActions: ['Busca una óptica por su nombre.', 'Crea una óptica nueva con su primera sucursal y la cuenta del dueño.', 'Escoge si está de prueba o con contrato, y qué partes del sistema puede usar.', 'Para cambiar su estado, escribe siempre el motivo.', 'Si una óptica pide ayuda, inicia una sesión de asistencia. Todo lo que hagas queda anotado.'],
      audience: 'admin',
    },
  ],
  roles: [
    { name: 'Dueño', description: 'Es el jefe de la óptica. Ve todo lo de sus sucursales y decide quién trabaja en el sistema.', permissions: ['Invitar y quitar trabajadores.', 'Poner los productos y los precios.', 'Ver ventas, cobros, producción, caja y números del negocio.', 'Hacer todo lo que hace un vendedor.'] },
    { name: 'Vendedor', description: 'Atiende a los clientes en el mostrador.', permissions: ['Registrar clientes y sus recetas.', 'Hacer ventas y cotizaciones.', 'Cobrar y entregar pedidos ya pagados.', 'Cerrar su propia caja.'] },
    { name: 'Cristalero o laboratorio', description: 'Hace los cristales. Solo ve los trabajos que le mandaron.', permissions: ['Ver la graduación que tiene que hacer.', 'Avisar cómo va el trabajo.', 'Reportar si algo salió mal.', 'No ve el nombre del cliente, ni precios, ni pagos.'] },
    { name: 'Montador', description: 'Monta los cristales en la armadura. Solo ve los trabajos que le mandaron.', permissions: ['Ver lo que tiene que montar.', 'Avisar cómo va el trabajo.', 'Reportar si algo salió mal.', 'No ve el nombre del cliente, ni precios, ni pagos.'] },
    { name: 'Equipo de LensSpace', description: 'Son los que dan de alta las ópticas y las ayudan. No venden ni trabajan dentro de tu óptica.', permissions: ['Crear ópticas nuevas.', 'Activar las partes del sistema que contrataste.', 'Ayudarte cuando lo pidas, dejando todo anotado.'] },
  ],
  workflows: [
    { title: 'Venderle unos espejuelos a un cliente', audience: 'end-user', steps: ['Toca «Nueva venta».', 'Busca al cliente o créalo con «Nuevo cliente».', 'Escoge su receta o toca «Nueva receta».', 'Escribe la tasa del día.', 'Toca la armadura y los cristales que quiere.', 'Dile al cliente el total.', 'Si dice que sí, toca «Cliente acepta · crear pedido».', 'Si deja dinero adelantado, anótalo y toca «Registrar pago».', 'Apunta el número del pedido y dáselo al cliente.'] },
    { title: 'Mandar a hacer los espejuelos y entregarlos', audience: 'end-user', steps: ['Ve a «Producción» y toca «Asignar trabajo».', 'Manda los cristales al cristalero.', 'Cuando estén hechos, toca «Marcar recibido» y revísalos.', 'Manda el montaje al montador.', 'Cuando vuelvan montados, toca «Marcar recibido» y «Marcar revisado».', 'Ve a «Pedidos y cobros» y toca «Avisar: listo para recoger».', 'Cuando venga el cliente, cobra lo que le falta.', 'Toca «Marcar como entregado».'] },
    { title: 'Cuando un trabajo sale mal', audience: 'end-user', steps: ['Abre el trabajo en «Producción».', 'Toca «Incidencia».', 'Explica con tus palabras qué pasó.', 'Escoge quién paga el arreglo.', 'Confirma.', 'El dueño o el vendedor toca «Aceptar repetición».', 'Manda el trabajo nuevo a quien lo va a hacer.', 'El trabajo malo se queda guardado para saber qué pasó.'] },
    { title: 'Cerrar la caja al final del día', audience: 'end-user', steps: ['Ve a «Caja y cierres».', 'Escoge tu caja y la moneda.', 'Cuenta los billetes que tienes.', 'Escribe lo que contaste.', 'Toca «Cerrar caja del día».', 'Si después te pagan algo más, vuelve y toca «Generar complementario».'] },
    { title: 'Darle acceso a un trabajador nuevo', audience: 'admin', steps: ['Ve a «Equipo».', 'Toca «Invitar miembro».', 'Escribe su nombre y su correo.', 'Escoge qué hace: vendedor, cristalero o montador.', 'Si es vendedor, escoge su sucursal.', 'Toca «Enviar invitación».', 'Dile que abra el correo y cree su contraseña.'] },
  ],
  faqs: [
    { question: '¿Por qué no me sale una opción en el menú?', answer: 'Cada persona ve solo lo que le toca según su trabajo. Si crees que te falta algo, pregúntale al dueño. Si eres el dueño, habla con el equipo de LensSpace.' },
    { question: '¿Puedo entregar unos espejuelos si el cliente no ha pagado todo?', answer: 'No. El sistema no te deja marcar el pedido como entregado hasta que el cliente pague completo.' },
    { question: 'Me equivoqué en una receta, ¿qué hago?', answer: 'Abre la receta y toca «Corregir». La receta vieja no se borra, se guarda en el historial con tu nombre.' },
    { question: '¿Qué pasa si cambian los precios después de darle el precio al cliente?', answer: 'El sistema te va a pedir que calcules otra vez. Dile al cliente el precio nuevo antes de confirmar.' },
    { question: '¿El cristalero o el montador ven cuánto pagó el cliente?', answer: 'No. Ellos solo ven lo que necesitan para hacer su trabajo: la graduación y el tipo de espejuelo.' },
    { question: 'Ya cerré la caja y me pagaron algo más, ¿qué hago?', answer: 'Cobra normal. Después vuelve a la caja y toca «Generar complementario». El primer cierre no se toca.' },
    { question: '¿Se puede borrar un cliente o un pedido?', answer: 'No. Todo queda guardado para que siempre se sepa qué pasó. Si un trabajador se va, se le quita el acceso, pero sus ventas se quedan.' },
    { question: '¿Qué es la tasa?', answer: 'Es cuántos pesos cubanos (CUP) vale 1 dólar (USD) ese día. La escribes en cada venta y el sistema la usa para sumar todo en CUP.' },
    { question: 'Se me fue la conexión, ¿perdí lo que hice?', answer: 'No te preocupes. El sistema te avisa cuando no hay conexión. Espera a que vuelva y repite lo último que hiciste; no se cobra dos veces.' },
  ],
  policies: ['Usa siempre tu propia cuenta. No le prestes tu contraseña a nadie.', 'Si usas una computadora de otra persona, cierra la sesión al terminar.', 'Si el precio cambia, díselo al cliente antes de confirmar.', 'No entregues espejuelos sin que el cliente haya pagado todo.', 'Si algo sale mal, anótalo en el sistema (no solo por WhatsApp) para que quede guardado.', 'No escribas contraseñas ni datos privados en las notas.'],
} satisfies ClientDocsInput
