'use client'

import { ChevronDown, ChevronUp, Plus, Trash2 } from 'lucide-react'
import { useRef, useState } from 'react'
import type { ClientDocsFaq, ClientDocsInput, ClientDocsModule, ClientDocsRole, ClientDocsWorkflow } from '../../generators/types'
import { moveBy, removeAt, replaceAt } from './listOps'

const field = 'mt-1 w-full rounded-[7px] border border-[#DCECEA] bg-[#FBFEFD] px-3 py-2 text-sm text-[#07322F] outline-none focus:border-[#0D7A72] focus:ring-4 focus:ring-[#E2F4F1]'
const Text = ({ label, value, onChange, area = false }: { label: string; value: string; onChange: (value: string) => void; area?: boolean }) => <label className="block text-xs font-semibold text-[#4A5B58]">{label}{area ? <textarea rows={3} value={value} onChange={(event) => onChange(event.target.value)} className={field} /> : <input value={value} onChange={(event) => onChange(event.target.value)} className={field} />}</label>
const Lines = ({ label, value, onChange }: { label: string; value: string[]; onChange: (value: string[]) => void }) => <Text label={label} area value={value.join('\n')} onChange={(next) => onChange(next.split('\n').filter(Boolean))} />

function ListEditor<T extends object>({ title, items, onChange, makeEmpty, itemTitle, render }: { title: string; items: T[]; onChange: (items: T[]) => void; makeEmpty: () => T; itemTitle: (item: T, index: number) => string; render: (item: T, update: (patch: Partial<T>) => void) => React.ReactNode }) {
  const counter = useRef(0)
  const [keys, setKeys] = useState(() => items.map((_, index) => `manual-initial-${index}`))
  const [openKey, setOpenKey] = useState<string | null>(null)
  const add = () => { const key = `manual-item-${counter.current++}`; setKeys([...keys, key]); onChange([...items, makeEmpty()]); setOpenKey(key) }
  const apply = (nextItems: T[], nextKeys: string[]) => { onChange(nextItems); setKeys(nextKeys) }
  return <section className="rounded-[10px] border border-[#DCECEA] bg-white"><header className="flex items-center justify-between border-b border-[#EEF5F4] px-4 py-3"><h3 className="font-display text-sm font-semibold text-[#07322F]">{title} <span className="text-[#74857F]">({items.length})</span></h3><button type="button" onClick={add} className="inline-flex items-center gap-1 rounded-[7px] bg-[#0D7A72] px-3 py-2 text-xs font-semibold text-white"><Plus size={14} /> Añadir</button></header><div className="space-y-2 p-3">{items.map((item, index) => { const key = keys[index] ?? `fallback-${index}`; const open = openKey === key; return <div key={key} className="rounded-[8px] border border-[#E3EFED] bg-[#FBFEFD]"><div className="flex items-center gap-1 p-2"><button type="button" onClick={() => setOpenKey(open ? null : key)} className="min-w-0 flex-1 truncate px-2 text-left text-sm font-semibold text-[#07322F]">{itemTitle(item, index) || 'Sin título'}</button><button type="button" aria-label="Mover arriba" disabled={!index} onClick={() => apply(moveBy(items, index, -1), moveBy(keys, index, -1))} className="p-1 text-[#74857F] disabled:opacity-30"><ChevronUp size={15} /></button><button type="button" aria-label="Mover abajo" disabled={index === items.length - 1} onClick={() => apply(moveBy(items, index, 1), moveBy(keys, index, 1))} className="p-1 text-[#74857F] disabled:opacity-30"><ChevronDown size={15} /></button><button type="button" aria-label="Eliminar" onClick={() => apply(removeAt(items, index), removeAt(keys, index))} className="p-1 text-[#C23C1C]"><Trash2 size={15} /></button></div>{open ? <div className="space-y-3 border-t border-[#EEF5F4] p-3">{render(item, (patch) => onChange(replaceAt(items, index, { ...item, ...patch })))}</div> : null}</div> })}</div></section>
}

export function ManualEditor({ input, onChange }: { input: ClientDocsInput; onChange: (input: ClientDocsInput) => void }) {
  const set = <K extends keyof ClientDocsInput>(key: K, value: ClientDocsInput[K]) => onChange({ ...input, [key]: value })
  return <div className="space-y-3 overflow-y-auto p-3">
    <section className="space-y-3 rounded-[10px] border border-[#DCECEA] bg-white p-4"><h3 className="font-display text-sm font-semibold text-[#07322F]">Datos generales</h3><Text label="Nombre de la aplicación" value={input.appName} onChange={(value) => set('appName', value)} /><Text label="Cliente o audiencia" value={input.clientName} onChange={(value) => set('clientName', value)} /><Text label="URL" value={input.appUrl} onChange={(value) => set('appUrl', value)} /></section>
    <ListEditor<ClientDocsModule> title="Módulos" items={input.modules} onChange={(value) => set('modules', value)} makeEmpty={() => ({ name: '', description: '', endUserActions: [] })} itemTitle={(item) => item.name} render={(item, update) => <><Text label="Nombre" value={item.name} onChange={(name) => update({ name })} /><Text label="Descripción" area value={item.description} onChange={(description) => update({ description })} /><Lines label="Acciones operativas (una por línea)" value={item.endUserActions} onChange={(endUserActions) => update({ endUserActions })} /><Lines label="Acciones administrativas (una por línea)" value={item.adminActions ?? []} onChange={(adminActions) => update({ adminActions })} /></>} />
    <ListEditor<ClientDocsRole> title="Roles" items={input.roles} onChange={(value) => set('roles', value)} makeEmpty={() => ({ name: '', description: '', permissions: [] })} itemTitle={(item) => item.name} render={(item, update) => <><Text label="Nombre" value={item.name} onChange={(name) => update({ name })} /><Text label="Descripción" area value={item.description} onChange={(description) => update({ description })} /><Lines label="Permisos (uno por línea)" value={item.permissions} onChange={(permissions) => update({ permissions })} /></>} />
    <ListEditor<ClientDocsWorkflow> title="Flujos" items={input.workflows} onChange={(value) => set('workflows', value)} makeEmpty={() => ({ title: '', audience: 'end-user', steps: [] })} itemTitle={(item) => item.title} render={(item, update) => <><Text label="Título" value={item.title} onChange={(title) => update({ title })} /><label className="block text-xs font-semibold text-[#4A5B58]">Audiencia<select value={item.audience} onChange={(event) => update({ audience: event.target.value as ClientDocsWorkflow['audience'] })} className={field}><option value="end-user">Personal operativo</option><option value="admin">Administración</option><option value="support">Soporte</option></select></label><Lines label="Pasos (uno por línea)" value={item.steps} onChange={(steps) => update({ steps })} /></>} />
    <ListEditor<ClientDocsFaq> title="Preguntas frecuentes" items={input.faqs} onChange={(value) => set('faqs', value)} makeEmpty={() => ({ question: '', answer: '' })} itemTitle={(item) => item.question} render={(item, update) => <><Text label="Pregunta" value={item.question} onChange={(question) => update({ question })} /><Text label="Respuesta" area value={item.answer} onChange={(answer) => update({ answer })} /></>} />
    <section className="rounded-[10px] border border-[#DCECEA] bg-white p-4"><Lines label="Políticas (una por línea)" value={input.policies ?? []} onChange={(policies) => set('policies', policies)} /></section>
  </div>
}
